Test unitaire
karned-rekipe/api-recipe pull request #11
Opened 2024-12-25 09:04 UTC by killiankopp

2024-12-25 18:29 UTC, killiankopp commented
#6

2025-01-06 09:10 UTC, heligonSeb requested changes

2025-01-06 09:10 UTC, heligonSeb commented on tests/services/test_items_service.py
> +    with pytest.raises(HTTPException):
tu raise une erreur ? c pas au test de la raise auto ?

2025-01-11 22:26 UTC, killiankopp commented on routers/items_router.py
> +async def create_new_item(request: Request, item: Item, repo=Depends(get_repo)) -> dict:
Je n'ai pas modifié la config de PyCharm et c'est lui qui fait la modifications des espaces avant et après le =. Il faudrait regarder ce qu'il faut faire ou pas et qu'on s'accorde car j'ai déjà remarqué que nous ne faisions pas la même chose.

2025-01-12 02:22 UTC, killiankopp commented on tests/models/test_ingredient_model.py
> +    assert ingredient.name == "Sugar"
ce n'est pas le but de ce test en particulier. On pourrait écrire un autre test pour cela et vérifier que la donnée est transformée si besoin.  là on veut vérifier que ce qu'on donne à l'objet est bien ce que l'on a à la sortie de l'objet une fois créé

2025-01-12 02:27 UTC, killiankopp commented on tests/services/test_items_service.py
> +    with pytest.raises(HTTPException):
Je voulais vérifier que j'avais un retour de create item si l'erreur venait en amont du repository

2025-01-12 10:07 UTC, killiankopp commented
J'ai ajouté un contrôle du typage sur Item. Les autres étaient déjà fait.

2025-01-14 10:43 UTC, heligonSeb approved these changes

2025-01-14 10:51 UTC, merged